### PR TITLE
WIP: cache tests

### PR DESCRIPTION
**Pull request by dnalborczyk**

### CODE REVIEW

**Comment by jdalton** [comment]
Rebase please.

**Comment by jdalton** [comment]
Any updates?

**Comment by dnalborczyk** [comment]
Hey John, yeah, I wanna add more tests ...

**Comment by jdalton** [comment]
There are node-chakracore fails with expected output. If you add debug to log out the `readdir` results we can see what it's doing.

**Comment by jdalton** [comment]
> btw, the SIGINT, SIGTERM test can be removed I suppose? this functionality is now gone?

Right.

**Comment by jdalton** [comment]
Thanks for opening this @dnalborczyk!

Imma merge this now and clean it up to clear it off pending PRs.

**Comment by dnalborczyk** [comment]
sounds good, sorry, was a little busy lately. we can add more tests along the way.

I got the test262 in a better shape with the `dynamic imports` locally. I think they are passing completely, the ones I skipped are either _incomplete_, or _wrong_ I believe, but I'd rather have you double check. I'll add a comment on the other PR later today.

**Comment by jdalton** [comment]
> sounds good, sorry, was a little busy lately. 

No worries!

>  I'll add a comment on the other PR later today.

Ok great! Ya, I wan to merge that one in soon too to avoid PR maintenance on it and to begin the process of knocking out the `esm` issues for them.

**Pull request merged**
