### PR TITLE
WIP: Add Windows to Travis.

### PR DESCRIPTION
**Pull request by dnalborczyk**
just a travis test run for windows support.

### CODE REVIEW

**Comment by jdalton** [comment]
Are you stuck on this @dnalborczyk?

**Comment by dnalborczyk** [comment]
hey @jdalton yeah, I'm planning on looking into the failure. wasn't sure if it's of any value, since you're using appveyor.

**Comment by dnalborczyk** [comment]
update: I got the failures reproduced on an older windows box. looking into it.

not sure if it's related to the use of `nvs` or git's handling of EOL (LF/CRLF) on Windows, or something completely different.

**Comment by jdalton** [comment]
Closing as stale.

**Pull request closed without merging**
