### PR TITLE
add hybrid module test

### PR DESCRIPTION
**Pull request by dnalborczyk**
scenario test case for https://github.com/standard-things/esm/issues/286

### CODE REVIEW

**Comment by jdalton** [comment]
Can you walk me through the scenario.

**Comment by dnalborczyk** [comment]
I really would if I could :smiley:

all I did was essentially "reverse engineer" what happened with https://github.com/standard-things/esm/issues/286

// hybrid module
import { execute, subscribe } from 'graphql'
// cjs module (has an internal dependency on graphql)
import apolloServerHapi from 'apollo-server-hapi'

essentially just getting rid of every dependency but the ones referenced. it seems my original assumption was wrong, as an esm/cjs hybrid referencing a cjs submodule was not the reason for the exception - that 1:1 scenario seemed to be always working. it was a combination of things I can't explain, like you had to reference a hybrid and a cjs, the cjs also had a dependency on the hybrid, BUT also - and that's the weird part (for me) - an additional dependency on another cjs ... and (only) then it was throwing if I remember correctly.

btw, doing all the above I discovered another bug. I'll have to digg it out later on, it was based on the above scenario.

**Comment by dnalborczyk** [comment]
one thing I forgot to mention:

I have 2 tests failing locally since yesterday (just pulled upstream).

I did `npm install` and `npm run test`.

running on macOS v10.13.4 beta, node v9.5.0.

```console
1) export declarations
       should support object rest/spread syntax:
     Unexpected token (6:14)
  std_esm_fork/test/fixture/export/object-rest-spread.mjs:6
  const abc = { ...identity(ab), c: "c" }

SyntaxError: Unexpected token
      at loader (file:///std_esm_fork/esm.js:14997:19)
      at /std_esm_fork/esm.js:4181:74
      at load (file:///std_esm_fork/esm.js:6207:3)
      at load (file:///std_esm_fork/esm.js:4151:80)
      at validate (file:///std_esm_fork/esm.js:12970:104)
      at tryValidateESM (file:///std_esm_fork/esm.js:12842:81)
      at compile (file:///std_esm_fork/esm.js:12699:7)
      at Module.compileWrapper (file:///std_esm_fork/esm.js:16719:89)
      at Module.child._compile (file:///std_esm_fork/esm.js:6203:22)
      at Object.methodWrapper (file:///std_esm_fork/esm.js:16753:11)
```

and 

```console
2) spec compliance
       should error when creating an `await` binding:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at checkErrorStack (/std_esm_fork/test/misc-tests.mjs:76:10)
      at _cf6‍.i.then.catch (/std_esm_fork/test/misc-tests.mjs:964:9)
      at <anonymous>
```

**Comment by jdalton** [comment]
@dnalborczyk Try running `npm run clean` and then `npm i`.

**Comment by dnalborczyk** [comment]
`npm run clean && npm install` didn't do it.

I did a **fresh upstream clone** [copy], **that worked**.

then I went back to the original fork folder, and tried:

`git fetch upstream && git reset --hard upstream/master`

still broken ...  :smiley:

I guess it's really nothing to worry about, just my curiousity ... maybe there's some _cache_ still lingering around.

**Comment by dnalborczyk** [comment]
@jdalton  found the sucker after a folder diff.

I had `src/vendor` only in the old folder, after deleting it, it worked!

can this be removed: https://github.com/standard-things/esm/blob/master/.gitignore#L14 ?

**Comment by jdalton** [comment]
Ah okay!

**Pull request merged**
