### PR TITLE
Babel interop tests

### PR DESCRIPTION
**Pull request by dnalborczyk**
added 2 simple scenario tests for babel-interop.

I created a new folder and used flow-types because I was thinking that class properties eventually will be integrated into the ecmascript spec. I could have also used jsx transforms. Feel free to rename things and move things around, I wasn't quite sure how the scenario and fixtures should be structured.

I run the first test with the v0.18 tagged version on master and it's passing. Didn't run on any other tags.

the second test is stalling, though it's working with the distributed build version (all versions I believe). Not sure if I'm doing something wrong.

on a different note:
I was wondering why the pm2 test is not failing and noticed that the pm2 scenario test is loading index.**js**, which is requiring std/esm, in addition pm2 passing the require std/esm flag to the node-args, is that intentional?

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @dnalborczyk!

**Comment by jdalton** [comment]
> I was wondering why the pm2 test is not failing and noticed that the pm2 scenario test is loading index.js, which is requiring std/esm, in addition pm2 passing the require std/esm flag to the node-args, is that intentional?

Ya the scenario was like that.

**Comment by dnalborczyk** [comment]
ah, I see, didn't think of double hooking.

btw, I just noticed that the path to [fixture/scenario/babel-register](https://github.com/standard-things/esm/pull/237/commits/8309d89e37045e405c46d4165675a5b2fcb8b6d7#diff-73a678f33a5fae1bd1ca46a51e424f69R36) should be ../babel-register-flow. I played with the babel-register folder to see why the test wasn't stalling, and forgot about it at the time of commit.

**Comment by jdalton** [comment]
> btw, I just noticed that the path to fixture/scenario/babel-register should be ../babel-register-flow.

No worries. Thanks for the PR!

**Pull request merged**
